In [5]:
import requests
import pandas as pd
import html5lib

url1 = 'https://www.basketball-reference.com/leagues/NBA_2022_totals.html'
total = pd.read_html(url1, header=0, attrs={'id':'totals_stats'})[0]

url2 = 'https://www.basketball-reference.com/awards/awards_2022.html'
mvp = pd.read_html(url2, header=1, attrs={'id':'mvp'})[0]

url3 = 'https://www.basketball-reference.com/leagues/NBA_2022_advanced.html'
advanced = pd.read_html(url3, header=0, attrs={'id':'advanced'})[0]

In [11]:
total_ = total.drop(['Rk', 'Age', 'Team', 'Pos', 'Awards'], axis=1).iloc[:-1]
total_ = total_.drop_duplicates(subset=['Player'], keep='first', ignore_index=True)
total_

,Player,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl
0,Trae Young,76.0,76.0,2652.0,711.0,1544.0,0.460,233.0,610.0,0.382,...,50.0,234.0,284.0,737.0,72.0,7.0,303.0,128.0,2155.0,0.0
1,DeMar DeRozan,76.0,76.0,2743.0,774.0,1535.0,0.504,50.0,142.0,0.352,...,56.0,336.0,392.0,374.0,68.0,24.0,181.0,178.0,2118.0,0.0
2,Joel Embiid,68.0,68.0,2297.0,666.0,1334.0,0.499,93.0,251.0,0.371,...,146.0,650.0,796.0,284.0,77.0,99.0,214.0,181.0,2079.0,2.0
3,Jayson Tatum,76.0,76.0,2731.0,708.0,1564.0,0.453,230.0,651.0,0.353,...,85.0,524.0,609.0,334.0,75.0,49.0,217.0,174.0,2046.0,0.0
4,Nikola Jokić,74.0,74.0,2476.0,764.0,1311.0,0.583,97.0,288.0,0.337,...,206.0,813.0,1019.0,584.0,109.0,63.0,281.0,191.0,2004.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,Jaysean Paige,1.0,0.0,7.0,0.0,3.0,0.000,0.0,2.0,0.000,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,2.0,0.0,0.0
601,Trayvon Palmer,1.0,0.0,17.0,0.0,1.0,0.000,0.0,0.0,NaN,...,0.0,2.0,2.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0
602,Emanuel Terry,3.0,0.0,18.0,0.0,5.0,0.000,0.0,0.0,NaN,...,8.0,7.0,15.0,2.0,1.0,0.0,5.0,4.0,0.0,0.0
603,Jon Teske,3.0,0.0,8.0,0.0,1.0,0.000,0.0,0.0,NaN,...,0.0,2.0,2.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
604,M.J. Walker,2.0,0.0,8.0,0.0,4.0,0.000,0.0,2.0,0.000,...,0.0,1.0,1.0,1.0,2.0,0.0,0.0,1.0,0.0,0.0

In [7]:
mvp_ = mvp.drop(['Rank', 'Age', 'Tm'], axis=1)
mvp_

,Player,First,Pts Won,Pts Max,Share,G,MP,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48
0,Nikola Jokić,65,875,1000,0.875,74,33.5,27.1,13.8,7.9,1.5,0.9,0.583,0.337,0.810,15.2,0.296
1,Joel Embiid,26,706,1000,0.706,68,33.8,30.6,11.7,4.2,1.1,1.5,0.499,0.371,0.814,12.0,0.252
2,Giannis Antetokounmpo,9,595,1000,0.595,67,32.9,29.9,11.6,5.8,1.1,1.4,0.553,0.293,0.722,12.9,0.281
3,Devin Booker,0,216,1000,0.216,68,34.5,26.8,5.0,4.8,1.1,0.4,0.466,0.383,0.868,7.6,0.156
4,Luka Dončić,0,146,1000,0.146,65,35.4,28.4,9.1,8.7,1.2,0.6,0.457,0.353,0.744,7.6,0.159
5,Jayson Tatum,0,43,1000,0.043,76,35.9,26.9,8.0,4.4,1.0,0.6,0.453,0.353,0.853,9.6,0.169
6,Ja Morant,0,10,1000,0.010,57,33.1,27.4,5.7,6.7,1.2,0.4,0.493,0.344,0.761,6.7,0.171
7,Stephen Curry,0,4,1000,0.004,64,34.5,25.5,5.2,6.3,1.3,0.4,0.437,0.380,0.923,8.0,0.173
8,Chris Paul,0,2,1000,0.002,65,32.9,14.7,4.4,10.8,1.9,0.3,0.493,0.317,0.837,9.4,0.210
9,DeMar DeRozan,0,1,1000,0.001,76,36.1,27.9,5.2,4.9,0.9,0.3,0.504,0.352,0.877,8.8,0.154
10,Kevin Durant,0,1,1000,0.001,55,37.2,29.9,7.4,6.4,0.9,0.9,0.518,0.383,0.910,8.4,0.198
11,LeBron James,0,1,1000,0.001,56,37.2,30.3,8.2,6.2,1.3,1.1,0.524,0.359,0.756,7.5,0.172

In [37]:
advanced_ = advanced.drop(['Rk', 'Age', 'Team', 'Pos', 'Awards'], axis=1).iloc[:-1].drop_duplicates(subset=['Player'], keep='first', ignore_index=True)
advanced_

,Player,G,GS,MP,PER,TS%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
0,Mikal Bridges,82.0,82.0,2854.0,14.4,0.627,0.364,0.183,2.9,10.0,6.5,8.7,1.6,1.1,6.8,15.0,5.2,3.7,8.9,0.150,0.5,1.1,1.6,2.6
1,Miles Bridges,80.0,80.0,2837.0,17.9,0.593,0.383,0.274,3.3,17.8,10.4,15.7,1.3,2.2,9.9,22.6,5.0,2.3,7.2,0.123,1.8,-0.3,1.5,2.5
2,DeMar DeRozan,76.0,76.0,2743.0,23.1,0.590,0.093,0.386,2.3,13.7,8.0,23.3,1.2,0.8,9.2,31.8,7.0,1.8,8.8,0.154,3.4,-0.9,2.5,3.1
3,Jayson Tatum,76.0,76.0,2731.0,21.8,0.578,0.416,0.300,3.5,20.2,12.1,21.1,1.4,1.6,10.9,32.1,5.0,4.6,9.6,0.169,4.3,0.6,5.0,4.8
4,Saddiq Bey,82.0,82.0,2704.0,14.0,0.529,0.537,0.224,4.1,14.1,8.8,13.8,1.3,0.5,7.1,21.3,2.4,1.6,4.0,0.071,0.9,-1.2,-0.3,1.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,Matt Mooney,1.0,0.0,2.0,-20.0,0.000,1.000,0.000,0.0,0.0,0.0,0.0,25.0,0.0,50.0,43.8,-0.1,0.0,0.0,-0.915,-33.9,11.5,-22.3,0.0
601,Ahmad Caver,1.0,0.0,1.0,76.2,1.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,42.8,0.0,0.0,0.0,1.204,31.0,5.9,36.9,0.0
602,Sam Dekker,1.0,0.0,1.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.003,-6.2,-3.4,-9.6,0.0
603,DeJon Jarreau,1.0,0.0,1.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,-0.022,-6.5,-1.5,-8.0,0.0
604,Ade Murkey,1.0,0.0,1.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,-0.017,-7.4,-2.3,-9.7,0.0

In [9]:
import os
year = 2023
file_name = '{}.csv'
mvp.to_csv(os.path.join('mvp-data/',file_name.format(year)))

In [48]:
adjusted_df = df.drop_duplicates(subset='Player', keep='first')
adjusted_df.drop(['Rk', 'Age', 'Team', 'Pos', 'Awards'], axis=1)

,Player,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl
0,Trae Young,76.0,76.0,2652.0,711.0,1544.0,0.460,233.0,610.0,0.382,...,50.0,234.0,284.0,737.0,72.0,7.0,303.0,128.0,2155.0,0.0
1,DeMar DeRozan,76.0,76.0,2743.0,774.0,1535.0,0.504,50.0,142.0,0.352,...,56.0,336.0,392.0,374.0,68.0,24.0,181.0,178.0,2118.0,0.0
2,Joel Embiid,68.0,68.0,2297.0,666.0,1334.0,0.499,93.0,251.0,0.371,...,146.0,650.0,796.0,284.0,77.0,99.0,214.0,181.0,2079.0,2.0
3,Jayson Tatum,76.0,76.0,2731.0,708.0,1564.0,0.453,230.0,651.0,0.353,...,85.0,524.0,609.0,334.0,75.0,49.0,217.0,174.0,2046.0,0.0
4,Nikola Jokić,74.0,74.0,2476.0,764.0,1311.0,0.583,97.0,288.0,0.337,...,206.0,813.0,1019.0,584.0,109.0,63.0,281.0,191.0,2004.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
808,Trayvon Palmer,1.0,0.0,17.0,0.0,1.0,0.000,0.0,0.0,NaN,...,0.0,2.0,2.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0
809,Emanuel Terry,3.0,0.0,18.0,0.0,5.0,0.000,0.0,0.0,NaN,...,8.0,7.0,15.0,2.0,1.0,0.0,5.0,4.0,0.0,0.0
810,Jon Teske,3.0,0.0,8.0,0.0,1.0,0.000,0.0,0.0,NaN,...,0.0,2.0,2.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
811,M.J. Walker,2.0,0.0,8.0,0.0,4.0,0.000,0.0,2.0,0.000,...,0.0,1.0,1.0,1.0,2.0,0.0,0.0,1.0,0.0,0.0
812,League Average,NaN,NaN,NaN,NaN,NaN,0.461,NaN,NaN,0.354,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
import pandas as pd
url4 = 'https://www.basketball-reference.com/leagues/NBA_2022_per_game.html'
per_game = pd.read_html(url4, header=0, attrs={'id':'per_game_stats'})[0]
per_game

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
0,1.0,Joel Embiid,27.0,PHI,C,68.0,68.0,33.8,9.8,19.6,...,2.1,9.6,11.7,4.2,1.1,1.5,3.1,2.7,30.6,"MVP-2,AS,NBA2"
1,2.0,LeBron James,37.0,LAL,C,56.0,56.0,37.2,11.4,21.8,...,1.1,7.1,8.2,6.2,1.3,1.1,3.5,2.2,30.3,"MVP-10,AS,NBA3"
2,3.0,Giannis Antetokounmpo,27.0,MIL,PF,67.0,67.0,32.9,10.3,18.6,...,2.0,9.6,11.6,5.8,1.1,1.4,3.3,3.2,29.9,"MVP-3,DPOY-6,AS,NBA1"
3,4.0,Kevin Durant,33.0,BRK,PF,55.0,55.0,37.2,10.5,20.3,...,0.5,6.9,7.4,6.4,0.9,0.9,3.5,2.1,29.9,"MVP-10,AS,NBA2"
4,5.0,Luka Dončić,22.0,DAL,PG,65.0,65.0,35.4,9.9,21.6,...,0.9,8.3,9.1,8.7,1.2,0.6,4.5,2.2,28.4,"MVP-5,AS,NBA1"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
808,602.0,Trayvon Palmer,27.0,DET,SG,1.0,0.0,17.0,0.0,1.0,...,0.0,2.0,2.0,0.0,0.0,0.0,1.0,2.0,0.0,NaN
809,603.0,Emanuel Terry,25.0,PHO,PF,3.0,0.0,6.0,0.0,1.7,...,2.7,2.3,5.0,0.7,0.3,0.0,1.7,1.3,0.0,NaN
810,604.0,Jon Teske,24.0,MEM,C,3.0,0.0,2.7,0.0,0.3,...,0.0,0.7,0.7,0.3,0.3,0.0,0.0,0.3,0.0,NaN
811,605.0,M.J. Walker,23.0,PHO,SG,2.0,0.0,4.0,0.0,2.0,...,0.0,0.5,0.5,0.5,1.0,0.0,0.0,0.5,0.0,NaN
812,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
per_game_ = per_game.drop(['Rk', 'Team', 'Age','Pos', 'Awards'], axis=1).iloc[:-1].drop_duplicates(subset=['Player'], keep='first', ignore_index=True)
per_game_2 = per_game_.add_suffix('PG').drop(columns=['GPG', 'GSPG'], axis=1).rename(columns={'PlayerPG':'Player'})
per_game_2

,Player,MPPG,FGPG,FGAPG,FG%PG,3PPG,3PAPG,3P%PG,2PPG,2PAPG,2P%PG,eFG%PG,FTPG,FTAPG,FT%PG,ORBPG,DRBPG,TRBPG,ASTPG,STLPG,BLKPG,TOVPG,PFPG,PTSPG
0,Joel Embiid,33.8,9.8,19.6,0.499,1.4,3.7,0.371,8.4,15.9,0.529,0.534,9.6,11.8,0.814,2.1,9.6,11.7,4.2,1.1,1.5,3.1,2.7,30.6
1,LeBron James,37.2,11.4,21.8,0.524,2.9,8.0,0.359,8.6,13.8,0.620,0.590,4.5,6.0,0.756,1.1,7.1,8.2,6.2,1.3,1.1,3.5,2.2,30.3
2,Giannis Antetokounmpo,32.9,10.3,18.6,0.553,1.1,3.6,0.293,9.2,15.0,0.616,0.582,8.3,11.4,0.722,2.0,9.6,11.6,5.8,1.1,1.4,3.3,3.2,29.9
3,Kevin Durant,37.2,10.5,20.3,0.518,2.1,5.5,0.383,8.4,14.8,0.568,0.570,6.8,7.4,0.910,0.5,6.9,7.4,6.4,0.9,0.9,3.5,2.1,29.9
4,Luka Dončić,35.4,9.9,21.6,0.457,3.1,8.8,0.353,6.8,12.8,0.528,0.529,5.6,7.5,0.744,0.9,8.3,9.1,8.7,1.2,0.6,4.5,2.2,28.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,Jaysean Paige,7.0,0.0,3.0,0.000,0.0,2.0,0.000,0.0,1.0,0.000,0.000,0.0,0.0,NaN,0.0,1.0,1.0,1.0,0.0,0.0,1.0,2.0,0.0
601,Trayvon Palmer,17.0,0.0,1.0,0.000,0.0,0.0,NaN,0.0,1.0,0.000,0.000,0.0,0.0,NaN,0.0,2.0,2.0,0.0,0.0,0.0,1.0,2.0,0.0
602,Emanuel Terry,6.0,0.0,1.7,0.000,0.0,0.0,NaN,0.0,1.7,0.000,0.000,0.0,0.0,NaN,2.7,2.3,5.0,0.7,0.3,0.0,1.7,1.3,0.0
603,Jon Teske,2.7,0.0,0.3,0.000,0.0,0.0,NaN,0.0,0.3,0.000,0.000,0.0,0.7,0.000,0.0,0.7,0.7,0.3,0.3,0.0,0.0,0.3,0.0
604,M.J. Walker,4.0,0.0,2.0,0.000,0.0,1.0,0.000,0.0,1.0,0.000,0.000,0.0,0.0,NaN,0.0,0.5,0.5,0.5,1.0,0.0,0.0,0.5,0.0

In [67]:
mvp_2 = mvp_.drop(columns=['MP','PTS','TRB','AST','STL','BLK','FG%','3P%','FT%'])
mvp_2

                   Player  First  Pts Won  Pts Max  Share   G    WS  WS/48
0            Nikola Jokić     65      875     1000  0.875  74  15.2  0.296
1             Joel Embiid     26      706     1000  0.706  68  12.0  0.252
2   Giannis Antetokounmpo      9      595     1000  0.595  67  12.9  0.281
3            Devin Booker      0      216     1000  0.216  68   7.6  0.156
4             Luka Dončić      0      146     1000  0.146  65   7.6  0.159
5            Jayson Tatum      0       43     1000  0.043  76   9.6  0.169
6               Ja Morant      0       10     1000  0.010  57   6.7  0.171
7           Stephen Curry      0        4     1000  0.004  64   8.0  0.173
8              Chris Paul      0        2     1000  0.002  65   9.4  0.210
9           DeMar DeRozan      0        1     1000  0.001  76   8.8  0.154
10           Kevin Durant      0        1     1000  0.001  55   8.4  0.198
11           LeBron James      0        1     1000  0.001  56   7.5  0.172

In [77]:
dummy =pd.merge(per_game_2, mvp_2, how='outer')
pd.set_option('display.max_columns', None)
dummy

,Player,MPPG,FGPG,FGAPG,FG%PG,3PPG,3PAPG,3P%PG,2PPG,2PAPG,2P%PG,eFG%PG,FTPG,FTAPG,FT%PG,ORBPG,DRBPG,TRBPG,ASTPG,STLPG,BLKPG,TOVPG,PFPG,PTSPG,First,Pts Won,Pts Max,Share,G,WS,WS/48
0,Joel Embiid,33.8,9.8,19.6,0.499,1.4,3.7,0.371,8.4,15.9,0.529,0.534,9.6,11.8,0.814,2.1,9.6,11.7,4.2,1.1,1.5,3.1,2.7,30.6,26.0,706.0,1000.0,0.706,68.0,12.0,0.252
1,LeBron James,37.2,11.4,21.8,0.524,2.9,8.0,0.359,8.6,13.8,0.620,0.590,4.5,6.0,0.756,1.1,7.1,8.2,6.2,1.3,1.1,3.5,2.2,30.3,0.0,1.0,1000.0,0.001,56.0,7.5,0.172
2,Giannis Antetokounmpo,32.9,10.3,18.6,0.553,1.1,3.6,0.293,9.2,15.0,0.616,0.582,8.3,11.4,0.722,2.0,9.6,11.6,5.8,1.1,1.4,3.3,3.2,29.9,9.0,595.0,1000.0,0.595,67.0,12.9,0.281
3,Kevin Durant,37.2,10.5,20.3,0.518,2.1,5.5,0.383,8.4,14.8,0.568,0.570,6.8,7.4,0.910,0.5,6.9,7.4,6.4,0.9,0.9,3.5,2.1,29.9,0.0,1.0,1000.0,0.001,55.0,8.4,0.198
4,Luka Dončić,35.4,9.9,21.6,0.457,3.1,8.8,0.353,6.8,12.8,0.528,0.529,5.6,7.5,0.744,0.9,8.3,9.1,8.7,1.2,0.6,4.5,2.2,28.4,0.0,146.0,1000.0,0.146,65.0,7.6,0.159
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,Jaysean Paige,7.0,0.0,3.0,0.000,0.0,2.0,0.000,0.0,1.0,0.000,0.000,0.0,0.0,NaN,0.0,1.0,1.0,1.0,0.0,0.0,1.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
601,Trayvon Palmer,17.0,0.0,1.0,0.000,0.0,0.0,NaN,0.0,1.0,0.000,0.000,0.0,0.0,NaN,0.0,2.0,2.0,0.0,0.0,0.0,1.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
602,Emanuel Terry,6.0,0.0,1.7,0.000,0.0,0.0,NaN,0.0,1.7,0.000,0.000,0.0,0.0,NaN,2.7,2.3,5.0,0.7,0.3,0.0,1.7,1.3,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
603,Jon Teske,2.7,0.0,0.3,0.000,0.0,0.0,NaN,0.0,0.3,0.000,0.000,0.0,0.7,0.000,0.0,0.7,0.7,0.3,0.3,0.0,0.0,0.3,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
604,M.J. Walker,4.0,0.0,2.0,0.000,0.0,1.0,0.000,0.0,1.0,0.000,0.000,0.0,0.0,NaN,0.0,0.5,0.5,0.5,1.0,0.0,0.0,0.5,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
dummy2 = pd.merge(total_, advanced_, how='outer')
dummy2

,Player,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,PER,TS%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
0,Trae Young,76.0,76.0,2652.0,711.0,1544.0,0.460,233.0,610.0,0.382,478.0,934.0,0.512,0.536,500.0,553.0,0.904,50.0,234.0,284.0,737.0,72.0,7.0,303.0,128.0,2155.0,0.0,25.4,0.603,0.395,0.358,2.1,9.6,5.9,46.7,1.3,0.2,14.5,34.4,9.0,1.0,10.0,0.181,7.1,-2.0,5.2,4.8
1,DeMar DeRozan,76.0,76.0,2743.0,774.0,1535.0,0.504,50.0,142.0,0.352,724.0,1393.0,0.520,0.521,520.0,593.0,0.877,56.0,336.0,392.0,374.0,68.0,24.0,181.0,178.0,2118.0,0.0,23.1,0.590,0.093,0.386,2.3,13.7,8.0,23.3,1.2,0.8,9.2,31.8,7.0,1.8,8.8,0.154,3.4,-0.9,2.5,3.1
2,Joel Embiid,68.0,68.0,2297.0,666.0,1334.0,0.499,93.0,251.0,0.371,573.0,1083.0,0.529,0.534,654.0,803.0,0.814,146.0,650.0,796.0,284.0,77.0,99.0,214.0,181.0,2079.0,2.0,31.2,0.616,0.188,0.602,7.2,31.1,19.4,23.5,1.7,3.9,11.3,37.2,7.9,4.1,12.0,0.252,7.2,2.0,9.2,6.5
3,Jayson Tatum,76.0,76.0,2731.0,708.0,1564.0,0.453,230.0,651.0,0.353,478.0,913.0,0.524,0.526,400.0,469.0,0.853,85.0,524.0,609.0,334.0,75.0,49.0,217.0,174.0,2046.0,0.0,21.8,0.578,0.416,0.300,3.5,20.2,12.1,21.1,1.4,1.6,10.9,32.1,5.0,4.6,9.6,0.169,4.3,0.6,5.0,4.8
4,Nikola Jokić,74.0,74.0,2476.0,764.0,1311.0,0.583,97.0,288.0,0.337,667.0,1023.0,0.652,0.620,379.0,468.0,0.810,206.0,813.0,1019.0,584.0,109.0,63.0,281.0,191.0,2004.0,19.0,32.8,0.661,0.220,0.357,9.6,35.5,23.0,42.6,2.2,2.3,15.6,31.9,10.8,4.5,15.2,0.296,9.2,4.5,13.7,9.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,Jaysean Paige,1.0,0.0,7.0,0.0,3.0,0.000,0.0,2.0,0.000,0.0,1.0,0.000,0.000,0.0,0.0,NaN,0.0,1.0,1.0,1.0,0.0,0.0,1.0,2.0,0.0,0.0,-22.2,0.000,0.667,0.000,0.0,16.3,7.7,18.1,0.0,0.0,25.0,24.5,-0.1,0.0,-0.1,-0.574,-25.0,-6.5,-31.5,0.0
601,Trayvon Palmer,1.0,0.0,17.0,0.0,1.0,0.000,0.0,0.0,NaN,0.0,1.0,0.000,0.000,0.0,0.0,NaN,0.0,2.0,2.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,-5.7,0.000,0.000,0.000,0.0,13.4,6.4,0.0,0.0,0.0,50.0,5.0,-0.1,0.0,0.0,-0.133,-13.1,-1.8,-15.0,-0.1
602,Emanuel Terry,3.0,0.0,18.0,0.0,5.0,0.000,0.0,0.0,NaN,0.0,5.0,0.000,0.000,0.0,0.0,NaN,8.0,7.0,15.0,2.0,1.0,0.0,5.0,4.0,0.0,0.0,-0.1,0.000,0.000,0.000,48.9,40.6,44.7,12.2,2.7,0.0,50.0,23.9,-0.1,0.0,-0.1,-0.256,-13.0,-5.3,-18.3,-0.1
603,Jon Teske,3.0,0.0,8.0,0.0,1.0,0.000,0.0,0.0,NaN,0.0,1.0,0.000,0.000,0.0,2.0,0.000,0.0,2.0,2.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.5,0.000,0.000,2.000,0.0,26.8,13.1,13.8,6.0,0.0,0.0,9.6,0.0,0.0,0.0,-0.080,-8.5,3.7,-4.8,0.0
604,M.J. Walker,2.0,0.0,8.0,0.0,4.0,0.000,0.0,2.0,0.000,0.0,2.0,0.000,0.000,0.0,0.0,NaN,0.0,1.0,1.0,1.0,2.0,0.0,0.0,1.0,0.0,0.0,-3.3,0.000,0.500,0.000,0.0,13.1,6.7,13.8,12.0,0.0,0.0,21.5,-0.1,0.0,0.0,-0.276,-15.8,6.2,-9.6,0.0

In [85]:
final = pd.merge(dummy, dummy2, how='outer', on='Player').fillna(0)
final['Pts Max'] = final['Pts Max'].max()
final['First Pts Share'] = final['First'] / final['Pts Max']
final['Year'] = 2022
final

,Player,MPPG,FGPG,FGAPG,FG%PG,3PPG,3PAPG,3P%PG,2PPG,2PAPG,2P%PG,eFG%PG,FTPG,FTAPG,FT%PG,ORBPG,DRBPG,TRBPG,ASTPG,STLPG,BLKPG,TOVPG,PFPG,PTSPG,First,Pts Won,Pts Max,Share,G_x,WS_x,WS/48_x,G_y,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,PER,TS%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,OWS,DWS,WS_y,WS/48_y,OBPM,DBPM,BPM,VORP,First Pts Share,Year
0,Joel Embiid,33.8,9.8,19.6,0.499,1.4,3.7,0.371,8.4,15.9,0.529,0.534,9.6,11.8,0.814,2.1,9.6,11.7,4.2,1.1,1.5,3.1,2.7,30.6,26.0,706.0,1000.0,0.706,68.0,12.0,0.252,68.0,68.0,2297.0,666.0,1334.0,0.499,93.0,251.0,0.371,573.0,1083.0,0.529,0.534,654.0,803.0,0.814,146.0,650.0,796.0,284.0,77.0,99.0,214.0,181.0,2079.0,2.0,31.2,0.616,0.188,0.602,7.2,31.1,19.4,23.5,1.7,3.9,11.3,37.2,7.9,4.1,12.0,0.252,7.2,2.0,9.2,6.5,0.026,2022
1,LeBron James,37.2,11.4,21.8,0.524,2.9,8.0,0.359,8.6,13.8,0.620,0.590,4.5,6.0,0.756,1.1,7.1,8.2,6.2,1.3,1.1,3.5,2.2,30.3,0.0,1.0,1000.0,0.001,56.0,7.5,0.172,56.0,56.0,2084.0,640.0,1221.0,0.524,161.0,448.0,0.359,479.0,773.0,0.620,0.590,254.0,336.0,0.756,63.0,396.0,459.0,349.0,73.0,59.0,196.0,121.0,1695.0,6.0,26.2,0.619,0.367,0.275,3.3,20.4,11.8,30.6,1.7,2.5,12.5,32.3,5.2,2.3,7.5,0.172,6.9,0.8,7.7,5.1,0.000,2022
2,Giannis Antetokounmpo,32.9,10.3,18.6,0.553,1.1,3.6,0.293,9.2,15.0,0.616,0.582,8.3,11.4,0.722,2.0,9.6,11.6,5.8,1.1,1.4,3.3,3.2,29.9,9.0,595.0,1000.0,0.595,67.0,12.9,0.281,67.0,67.0,2204.0,689.0,1245.0,0.553,71.0,242.0,0.293,618.0,1003.0,0.616,0.582,553.0,766.0,0.722,134.0,644.0,778.0,388.0,72.0,91.0,219.0,212.0,2002.0,4.0,32.1,0.633,0.194,0.615,6.6,30.4,18.7,31.7,1.6,4.0,12.2,34.9,9.2,3.7,12.9,0.281,7.6,3.5,11.2,7.4,0.009,2022
3,Kevin Durant,37.2,10.5,20.3,0.518,2.1,5.5,0.383,8.4,14.8,0.568,0.570,6.8,7.4,0.910,0.5,6.9,7.4,6.4,0.9,0.9,3.5,2.1,29.9,0.0,1.0,1000.0,0.001,55.0,8.4,0.198,55.0,55.0,2047.0,578.0,1115.0,0.518,115.0,300.0,0.383,463.0,815.0,0.568,0.570,372.0,409.0,0.910,29.0,378.0,407.0,351.0,48.0,52.0,191.0,113.0,1643.0,4.0,25.6,0.634,0.269,0.367,1.6,19.6,10.8,29.1,1.1,2.3,12.9,31.2,6.4,2.0,8.4,0.198,6.4,0.7,7.2,4.8,0.000,2022
4,Luka Dončić,35.4,9.9,21.6,0.457,3.1,8.8,0.353,6.8,12.8,0.528,0.529,5.6,7.5,0.744,0.9,8.3,9.1,8.7,1.2,0.6,4.5,2.2,28.4,0.0,146.0,1000.0,0.146,65.0,7.6,0.159,65.0,65.0,2301.0,641.0,1403.0,0.457,201.0,569.0,0.353,440.0,834.0,0.528,0.529,364.0,489.0,0.744,56.0,537.0,593.0,568.0,75.0,36.0,292.0,145.0,1847.0,10.0,25.1,0.571,0.406,0.349,2.7,26.0,14.3,46.0,1.6,1.4,15.3,37.4,3.8,3.8,7.6,0.159,6.4,1.8,8.2,5.9,0.000,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,Jaysean Paige,7.0,0.0,3.0,0.000,0.0,2.0,0.000,0.0,1.0,0.000,0.000,0.0,0.0,0.000,0.0,1.0,1.0,1.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,1000.0,0.000,0.0,0.0,0.000,1.0,0.0,7.0,0.0,3.0,0.000,0.0,2.0,0.000,0.0,1.0,0.000,0.000,0.0,0.0,0.000,0.0,1.0,1.0,1.0,0.0,0.0,1.0,2.0,0.0,0.0,-22.2,0.000,0.667,0.000,0.0,16.3,7.7,18.1,0.0,0.0,25.0,24.5,-0.1,0.0,-0.1,-0.574,-25.0,-6.5,-31.5,0.0,0.000,2022
601,Trayvon Palmer,17.0,0.0,1.0,0.000,0.0,0.0,0.000,0.0,1.0,0.000,0.000,0.0,0.0,0.000,0.0,2.0,2.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,1000.0,0.000,0.0,0.0,0.000,1.0,0.0,17.0,0.0,1.0,0.000,0.0,0.0,0.000,0.0,1.0,0.000,0.000,0.0,0.0,0.000,0.0,2.0,2.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,-5.7,0.000,0.000,0.000,0.0,13.4,6.4,0.0,0.0,0.0,50.0,5.0,-0.1,0.0,0.0,-0.133,-13.1,-1.8,-15.0,-0.1,0.000,2022
602,Emanuel Terry,6.0,0.0,1.7,0.000,0.0,0.0,0.000,0.0,1.7,0.000,0.000,0.0,0.0,0.000,2.7,2.3,5.0,0.7,0.3,0.0,1.7,1.3,0.0,0.0,0.0,1000.0,0.000,0.0,0.0,0.000,3.0,0.0,18.0,0.0,5.0,0.000,0.0,0.0,0.000,0.0,5.0,0.000,0.000,0.0,0.0,0.000,8.0,7.0,15.0,2.0,1.0,0.0,5.0,4.0,0.0,0.0,-0.1,0.000,0.000,0.000,48.9,40.6,44.7,12.2,2.7,0.0,50.0,23.9,-0.1,0.0,-0.1,-0.256,-13.0,-5.3,-18.3,-0.1,0.000,2022
603,Jon Teske,2.7,0.0,0.3,0.000,0.0,0.0,0.000,0.0,0.3,0.000,0.000,0.0,0.7,0.000,0.0,0.7,0.7,0.3,0.3,0.0,0.0,0.3,0.0,0.0,0.0,1000.0,0.000,0.0,0.0,0.000,3.0,0.0,8.0,0.0,1.0,0.000,0.0,0.0,0.000,0.0,1.0,0.000,0.000,0.0,2.0,0.000,0.0,2.0,2.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.5,0.000,0.000,2.000,0.0,26.8,13.1,13.8,6.0,0.0,0.0,9.6,0.0,0.0,0.0,-0.080,-8.5,3.7,-4.8,0.0,0.000,2022
604,M.J. Walker,4.0,0.0,2.0,0.000,0.0,1.0,0.000,0.0,1.0,0.000,0.000,0.0,0.0,0.000,0.0,0.5,0.5,0.5,1.0,0.0,0.0,0.5,0.0,0.0,0.0,1000.0,0.000,0.0,0.0,0.000,2.0,0.0,8.0,0.0,4.0,0.000,0.0,2.0,0.000,0.0,2.0,0.000,0.000,0.0,0.0,0.000,0.0,1.0,1.0,1.0,2.0,0.0,0.0,1.0,0.0,0.0,-3.3,0.000,0.500,0.000,0.0,13.1,6.7,13.8,12.0,0.0,0.0,21.5,-0.1,0.0,0.0,-0.276,-15.8,6.2,-9.6,0.0,0.000,2022