In [20]:
import pandas as pd
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error

In [12]:
df = pd.read_csv('data.csv')
df = df.sort_values(by=['Year', 'Share'], ascending=[True, False])
df

,Player,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,...,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Share,Year
0,Kevin Garnett,82.0,82.0,3231.0,804.0,1611.0,0.499,11.0,43.0,0.256,...,10.4,8.0,18.3,0.272,6.8,3.3,10.2,10.0,0.991,2004
14,Tim Duncan,69.0,68.0,2527.0,592.0,1181.0,0.501,2.0,12.0,0.167,...,5.9,7.2,13.1,0.249,5.2,3.3,8.5,6.7,0.582,2004
12,Jermaine O'Neal,78.0,78.0,2788.0,608.0,1400.0,0.434,2.0,18.0,0.111,...,2.7,6.3,9.0,0.155,1.1,1.3,2.4,3.1,0.425,2004
1,Peja Stojaković,81.0,81.0,3264.0,665.0,1386.0,0.480,240.0,554.0,0.433,...,11.4,2.1,13.5,0.198,5.2,-1.3,3.9,4.9,0.228,2004
13,Kobe Bryant,65.0,64.0,2447.0,516.0,1178.0,0.438,71.0,217.0,0.327,...,7.8,3.0,10.7,0.210,5.1,0.5,5.6,4.7,0.172,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10343,Danny Green,2.0,0.0,18.0,0.0,2.0,0.000,0.0,1.0,0.000,...,0.0,0.0,0.0,-0.035,-7.4,0.8,-6.6,0.0,0.000,2024
10344,Ron Harper Jr.,1.0,0.0,4.0,0.0,0.0,0.000,0.0,0.0,0.000,...,0.0,0.0,0.0,0.087,-11.7,2.8,-8.8,0.0,0.000,2024
10345,Justin Jackson,2.0,0.0,1.0,0.0,0.0,0.000,0.0,0.0,0.000,...,0.0,0.0,0.0,0.031,-6.3,-1.2,-7.5,0.0,0.000,2024
10346,Dmytro Skapintsev,2.0,0.0,2.0,0.0,1.0,0.000,0.0,0.0,0.000,...,0.0,0.0,0.0,-0.483,-16.0,-9.8,-25.9,0.0,0.000,2024
10347,Javonte Smart,1.0,0.0,1.0,0.0,0.0,0.000,0.0,0.0,0.000,...,0.0,0.0,0.0,0.005,-6.2,-2.1,-8.3,0.0,0.000,2024

In [21]:
# Experiment Cell
pd.concat([df[df['Year'] == 2004], df[df['Year'] == 2005]])
features = df.columns.to_list()
features = [feature for feature in df.columns.to_list() if feature not in ['Player', 'Share', 'Year']]
df[features]
df[df['Year'] == 2024]

,Player,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,...,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Share,Year
9780,Nikola Jokić,79.0,79.0,2737.0,822.0,1411.0,0.583,83.0,231.0,0.359,...,12.0,5.1,17.0,0.299,9.0,4.2,13.2,10.6,0.935,2024
9777,Shai Gilgeous-Alexander,75.0,75.0,2553.0,796.0,1487.0,0.535,95.0,269.0,0.353,...,10.5,4.2,14.6,0.275,6.7,2.3,9.0,7.1,0.646,2024
9776,Luka Dončić,70.0,70.0,2624.0,804.0,1652.0,0.487,284.0,744.0,0.382,...,8.5,3.5,12.0,0.220,8.3,1.7,9.9,8.0,0.572,2024
9778,Giannis Antetokounmpo,73.0,73.0,2567.0,837.0,1369.0,0.611,34.0,124.0,0.274,...,9.5,3.7,13.2,0.246,6.7,2.4,9.0,7.2,0.194,2024
9779,Jalen Brunson,77.0,77.0,2726.0,790.0,1648.0,0.479,211.0,526.0,0.401,...,8.8,2.4,11.2,0.198,6.3,-0.4,5.8,5.4,0.143,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10343,Danny Green,2.0,0.0,18.0,0.0,2.0,0.000,0.0,1.0,0.000,...,0.0,0.0,0.0,-0.035,-7.4,0.8,-6.6,0.0,0.000,2024
10344,Ron Harper Jr.,1.0,0.0,4.0,0.0,0.0,0.000,0.0,0.0,0.000,...,0.0,0.0,0.0,0.087,-11.7,2.8,-8.8,0.0,0.000,2024
10345,Justin Jackson,2.0,0.0,1.0,0.0,0.0,0.000,0.0,0.0,0.000,...,0.0,0.0,0.0,0.031,-6.3,-1.2,-7.5,0.0,0.000,2024
10346,Dmytro Skapintsev,2.0,0.0,2.0,0.0,1.0,0.000,0.0,0.0,0.000,...,0.0,0.0,0.0,-0.483,-16.0,-9.8,-25.9,0.0,0.000,2024
10347,Javonte Smart,1.0,0.0,1.0,0.0,0.0,0.000,0.0,0.0,0.000,...,0.0,0.0,0.0,0.005,-6.2,-2.1,-8.3,0.0,0.000,2024

In [14]:
def df_concat_stats(df, startYear, endYear):
    final_df = pd.DataFrame()
    if startYear == endYear:
        return df
    while startYear <= endYear:
        if final_df.empty:
            final_df = df[df['Year'] == startYear]
        else:
            final_df = pd.concat([final_df, df[df['Year'] == startYear]])
        startYear +=1
    return final_df

# TESTS #
test = df_concat_stats(df, 2004, 2004)
test.iloc[0:5]['Player'].tolist()

['Kevin Garnett',
 'Tim Duncan',
 "Jermaine O'Neal",
 'Peja Stojaković',
 'Kobe Bryant']

In [19]:
years = range(2005, 2025)

results = []

features = [feature for feature in df.columns.to_list() if feature not in ['Player', 'Share', 'Year']]

right = 0
wrong = 0

for year in years:
    model = XGBRegressor(random_state=42)

    train_df = df_concat_stats(df, 2004, year-1)
    test_df = df[df['Year'] == year]
    
    X_train = train_df[features]
    y_train = train_df['Share']
    
    X_test = test_df[features]
    y_test = test_df['Share']

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_pred, y_test)
    
    test_copy = test_df.copy()
    test_copy['Predicted Share'] = y_pred
    actual_mvp = test_copy.sort_values('Share', ascending=False).iloc[0]['Player']
    predicted_mvp = test_copy.sort_values('Predicted Share', ascending=False).iloc[0]['Player']
    top_five = test_copy.sort_values('Predicted Share', ascending=False).iloc[0:5]['Player'].to_list()
    
    
    results.append({
        "Train Years": [2004, year-1],
        "Test Year": year,
        "MSE": mse,
        "Predicted MVP": predicted_mvp,
        "Actual MVP": actual_mvp,
        "Top Five": top_five
    })

    
    if predicted_mvp == actual_mvp:
        right += 1
    else:
        wrong += 1

print("Right: " + str(right) + ", Wrong: " + str(wrong))
results

Right: 10, Wrong: 10

[{'Train Years': [2004, 2004],
  'Test Year': 2005,
  'MSE': 7.256673105584919e-08,
  'Predicted MVP': 'Steve Nash',
  'Actual MVP': 'Steve Nash',
  'Top Five': ['Steve Nash',
   "Shaquille O'Neal",
   'Dirk Nowitzki',
   'Tim Duncan',
   'Allen Iverson']},
 {'Train Years': [2004, 2005],
  'Test Year': 2006,
  'MSE': 0.001999417547542164,
  'Predicted MVP': 'Ray Allen',
  'Actual MVP': 'Steve Nash',
  'Top Five': ['Ray Allen',
   'Elton Brand',
   'Steve Nash',
   'Kevin Garnett',
   'Dirk Nowitzki']},
 {'Train Years': [2004, 2006],
  'Test Year': 2007,
  'MSE': 0.00103917250875013,
  'Predicted MVP': 'Steve Nash',
  'Actual MVP': 'Dirk Nowitzki',
  'Top Five': ['Steve Nash',
   'Dirk Nowitzki',
   'Tim Duncan',
   'Dwyane Wade',
   'Kobe Bryant']},
 {'Train Years': [2004, 2007],
  'Test Year': 2008,
  'MSE': 0.0028254075478178087,
  'Predicted MVP': 'Chris Paul',
  'Actual MVP': 'Kobe Bryant',
  'Top Five': ['Chris Paul',
   'Chauncey Billups',
   'LeBron James',
   "Amar'e Stoudemire",
   'Dwight Howard']},
 {'Train Years': [2004, 2008],
  'Test Year': 2009,
  'MSE': 0.001920515713873352,
  'Predicted MVP': 'LeBron James',
  'Actual MVP': 'LeBron James',
  'Top Five': ['LeBron James',
   'Chris Paul',
   'Dwyane Wade',
   'Dwight Howard',
   'Brandon Roy']},
 {'Train Years': [2004, 2009],
  'Test Year': 2010,
  'MSE': 0.0015539443970573892,
  'Predicted MVP': 'LeBron James',
  'Actual MVP': 'LeBron James',
  'Top Five': ['LeBron James',
   'Kevin Durant',
   'Gerald Wallace',
   'Dwight Howard',
   'Dwyane Wade']},
 {'Train Years': [2004, 2010],
  'Test Year': 2011,
  'MSE': 0.0016402590242007317,
  'Predicted MVP': 'Derrick Rose',
  'Actual MVP': 'Derrick Rose',
  'Top Five': ['Derrick Rose',
   'Chris Paul',
   'Dwight Howard',
   'Pau Gasol',
   'LeBron James']},
 {'Train Years': [2004, 2011],
  'Test Year': 2012,
  'MSE': 0.0032872022007627262,
  'Predicted MVP': 'Dwight Howard',
  'Actual MVP': 'LeBron James',
  'Top Five': ['Dwight Howard',
   'Rajon Rondo',
   'LeBron James',
   'Chris Paul',
   'Kevin Durant']},
 {'Train Years': [2004, 2012],
  'Test Year': 2013,
  'MSE': 0.0006767878006619485,
  'Predicted MVP': 'LeBron James',
  'Actual MVP': 'LeBron James',
  'Top Five': ['LeBron James',
   'Kevin Durant',
   'Chris Paul',
   'Carmelo Anthony',
   'James Harden']},
 {'Train Years': [2004, 2013],
  'Test Year': 2014,
  'MSE': 0.001753287028589506,
  'Predicted MVP': 'LeBron James',
  'Actual MVP': 'Kevin Durant',
  'Top Five': ['LeBron James',
   'Kevin Durant',
   'Stephen Curry',
   'Kevin Love',
   'Al Jefferson']},
 {'Train Years': [2004, 2014],
  'Test Year': 2015,
  'MSE': 0.0018096079250800269,
  'Predicted MVP': 'James Harden',
  'Actual MVP': 'Stephen Curry',
  'Top Five': ['James Harden',
   'Chris Paul',
   'Anthony Davis',
   'Stephen Curry',
   'DeAndre Jordan']},
 {'Train Years': [2004, 2015],
  'Test Year': 2016,
  'MSE': 0.0029200468257647425,
  'Predicted MVP': 'Kevin Durant',
  'Actual MVP': 'Stephen Curry',
  'Top Five': ['Kevin Durant',
   'Stephen Curry',
   'LeBron James',
   'Rajon Rondo',
   'James Harden']},
 {'Train Years': [2004, 2016],
  'Test Year': 2017,
  'MSE': 0.0014215755665370248,
  'Predicted MVP': 'Kawhi Leonard',
  'Actual MVP': 'Russell Westbrook',
  'Top Five': ['Kawhi Leonard',
   'Russell Westbrook',
   'LeBron James',
   'James Harden',
   'Anthony Davis']},
 {'Train Years': [2004, 2017],
  'Test Year': 2018,
  'MSE': 0.0016066773895703182,
  'Predicted MVP': 'James Harden',
  'Actual MVP': 'James Harden',
  'Top Five': ['James Harden',
   'Giannis Antetokounmpo',
   'Kevin Durant',
   'LaMarcus Aldridge',
   'Anthony Davis']},
 {'Train Years': [2004, 2018],
  'Test Year': 2019,
  'MSE': 0.0015145286323676934,
  'Predicted MVP': 'Giannis Antetokounmpo',
  'Actual MVP': 'Giannis Antetokounmpo',
  'Top Five': ['Giannis Antetokounmpo',
   'LeBron James',
   'James Harden',
   'Joel Embiid',
   'Kawhi Leonard']},
 {'Train Years': [2004, 2019],
  'Test Year': 2020,
  'MSE': 0.0014212060333359472,
  'Predicted MVP': 'Giannis Antetokounmpo',
  'Actual MVP': 'Giannis Antetokounmpo',
  'Top Five': ['Giannis Antetokounmpo',
   'James Harden',
   'Damian Lillard',
   'LeBron James',
   'Bradley Beal']},
 {'Train Years': [2004, 2020],
  'Test Year': 2021,
  'MSE': 0.001874238193128295,
  'Predicted MVP': 'Nikola Jokić',
  'Actual MVP': 'Nikola Jokić',
  'Top Five': ['Nikola Jokić',
   'Zion Williamson',
   'Giannis Antetokounmpo',
   'Kevin Durant',
   'Bradley Beal']},
 {'Train Years': [2004, 2021],
  'Test Year': 2022,
  'MSE': 0.0003800659009581487,
  'Predicted MVP': 'Giannis Antetokounmpo',
  'Actual MVP': 'Nikola Jokić',
  'Top Five': ['Giannis Antetokounmpo',
   'Nikola Jokić',
   'Joel Embiid',
   'Luka Dončić',
   'Trae Young']},
 {'Train Years': [2004, 2022],
  'Test Year': 2023,
  'MSE': 0.0016793807516405532,
  'Predicted MVP': 'Joel Embiid',
  'Actual MVP': 'Joel Embiid',
  'Top Five': ['Joel Embiid',
   'Luka Dončić',
   'Giannis Antetokounmpo',
   'Jimmy Butler',
   'Nikola Jokić']},
 {'Train Years': [2004, 2023],
  'Test Year': 2024,
  'MSE': 0.0014034967298703284,
  'Predicted MVP': 'Shai Gilgeous-Alexander',
  'Actual MVP': 'Nikola Jokić',
  'Top Five': ['Shai Gilgeous-Alexander',
   'Nikola Jokić',
   'Giannis Antetokounmpo',
   'Joel Embiid',
   'Domantas Sabonis']}]