In [126]:
import pandas as pd

In [127]:
# Webscrape links into dataframes
player_stats = pd.read_html('https://www.basketball-reference.com/leagues/NBA_2024_advanced.html', header=0, attrs={'id':'advanced'})[0]
player_stats2 = pd.read_html('https://www.basketball-reference.com/leagues/NBA_2024_totals.html', header=0, attrs={'id':'totals_stats'})[0]
east_stats = pd.read_html('https://www.basketball-reference.com/leagues/NBA_2024.html', header=0, attrs={'id':'confs_standings_E'})[0]
west_stats = pd.read_html('https://www.basketball-reference.com/leagues/NBA_2024.html', header=0, attrs={'id':'confs_standings_W'})[0]
mvp_stats = pd.read_html('https://www.basketball-reference.com/awards/awards_2024.html', header=1, attrs={'id':'mvp'})[0]

In [128]:
# Variables
nba_teams = {
    "Atlanta Hawks": "ATL",
    "Boston Celtics": "BOS",
    "Brooklyn Nets": "BRK",  # Sometimes "BKN"
    "Chicago Bulls": "CHI",
    "Charlotte Hornets": "CHO",  # Sometimes "CHA"
    "Cleveland Cavaliers": "CLE",
    "Dallas Mavericks": "DAL",
    "Denver Nuggets": "DEN",
    "Detroit Pistons": "DET",
    "Golden State Warriors": "GSW",
    "Houston Rockets": "HOU",
    "Indiana Pacers": "IND",
    "Los Angeles Clippers": "LAC",
    "Los Angeles Lakers": "LAL",
    "Memphis Grizzlies": "MEM",
    "Miami Heat": "MIA",
    "Milwaukee Bucks": "MIL",
    "Minnesota Timberwolves": "MIN",
    "New Orleans Pelicans": "NOP",
    "New York Knicks": "NYK",
    "Oklahoma City Thunder": "OKC",
    "Orlando Magic": "ORL",
    "Philadelphia 76ers": "PHI",
    "Phoenix Suns": "PHO",
    "Portland Trail Blazers": "POR",
    "Sacramento Kings": "SAC",
    "San Antonio Spurs": "SAS",
    "Toronto Raptors": "TOR",
    "Utah Jazz": "UTA",
    "Washington Wizards": "WAS"
}

In [169]:
# Feature Selection/Engineering
east_stats_ = east_stats.rename(columns={'Eastern Conference':'Team'}).loc[:,['Team', 'W/L%']]
east_stats_['Team'] = east_stats_['Team'].str.replace('*','', regex=True)
east_stats_['Seed'] = east_stats.index + 1
west_stats_ = west_stats.rename(columns={'Western Conference':'Team'}).loc[:,['Team', 'W/L%']]
west_stats_['Team'] = west_stats_['Team'].str.replace('*','', regex=True)
west_stats_['Seed'] = west_stats.index + 1

team_stats_ = pd.concat([east_stats_, west_stats_])
team_stats_.replace(nba_teams, inplace=True)

player_stats_ = player_stats.loc[:,['Player', 'Team', 'G', 'GS', 'MP', 'PER', 'TS%',
       '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%','USG%', 'OWS', 'DWS', 'WS', 'WS/48', 'OBPM', 'DBPM', 'BPM', 'VORP']].iloc[:-1]
player_stats_['MP'] = round(player_stats_['MP'] / player_stats_['G'], 1)
player_stats_.drop_duplicates('Player', keep='first', inplace=True)

player_stats_teams = player_stats.copy()
player_stats_teams = player_stats_teams.loc[:, ['Player', 'Team']]
player_stats_teams.drop_duplicates('Player', keep='last', inplace=True)

player_stats_2 = player_stats2.loc[:, ['Player','FGA', 'FG%', '3P%', 'FT%','eFG%', 'PTS']].iloc[:-1]
player_stats_2.drop_duplicates('Player', keep='first', inplace=True)
player_stats_ = player_stats_.merge(player_stats_teams, on='Player', suffixes=('', '_Correct'))
player_stats_['Team'] = player_stats_['Team_Correct']
player_stats_.drop(columns=['Team_Correct'], inplace=True)

mvp_stats_ = mvp_stats.loc[:,['Player', 'Tm', 'Share', 'MP', 'FG%', '3P%', 'FT%', 'WS', 'WS/48']]
mvp_stats_.rename(columns={'Tm':'Team'}, inplace=True)
#mvp_stats_['Tm'].replace(nba_teams, inplace=True)
mvp_stats_

                    Player Team  Share    MP    FG%    3P%    FT%    WS  WS/48
0             Nikola Jokić  DEN  0.935  34.6  0.583  0.359  0.817  17.0  0.299
1  Shai Gilgeous-Alexander  OKC  0.646  34.0  0.535  0.353  0.874  14.6  0.275
2              Luka Dončić  DAL  0.572  37.5  0.487  0.382  0.786  12.0  0.220
3    Giannis Antetokounmpo  MIL  0.194  35.2  0.611  0.274  0.657  13.2  0.246
4            Jalen Brunson  NYK  0.143  35.4  0.479  0.401  0.847  11.2  0.198
5             Jayson Tatum  BOS  0.087  35.7  0.471  0.376  0.833  10.4  0.189
6          Anthony Edwards  MIN  0.018  35.1  0.461  0.357  0.836   7.5  0.130
7         Domantas Sabonis  SAC  0.003  35.7  0.594  0.379  0.704  12.6  0.206
8             Kevin Durant  PHO  0.001  37.2  0.523  0.413  0.856   8.3  0.142

In [170]:
display(team_stats_)
display(player_stats_)
display(player_stats_2)

   Team   W/L%  Seed
0   BOS  0.780     1
1   NYK  0.610     2
2   MIL  0.598     3
3   CLE  0.585     4
4   ORL  0.573     5
5   IND  0.573     6
6   PHI  0.573     7
7   MIA  0.561     8
8   CHI  0.476     9
9   ATL  0.439    10
10  BRK  0.390    11
11  TOR  0.305    12
12  CHO  0.256    13
13  WAS  0.183    14
14  DET  0.171    15
0   OKC  0.695     1
1   DEN  0.695     2
2   MIN  0.683     3
3   LAC  0.622     4
4   DAL  0.610     5
5   PHO  0.598     6
6   NOP  0.598     7
7   LAL  0.573     8
8   SAC  0.561     9
9   GSW  0.561    10
10  HOU  0.500    11
11  UTA  0.378    12
12  MEM  0.329    13
13  SAS  0.268    14
14  POR  0.256    15

,Player,Team,G,GS,MP,PER,TS%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
0,DeMar DeRozan,CHI,79.0,79.0,37.8,19.7,0.584,0.166,0.452,1.6,11.3,6.4,21.8,1.5,1.5,7.7,25.8,7.0,2.2,9.2,0.147,2.1,-0.3,1.8,2.8
1,Domantas Sabonis,SAC,82.0,82.0,35.7,23.2,0.637,0.081,0.389,11.0,32.3,21.4,33.9,1.2,1.5,17.9,22.2,8.6,4.0,12.6,0.206,4.0,2.4,6.5,6.2
2,Coby White,CHI,79.0,78.0,36.5,14.5,0.570,0.460,0.215,1.7,12.4,6.9,20.8,0.9,0.6,11.1,22.7,3.1,1.6,4.7,0.078,0.7,-1.3,-0.7,0.9
3,Mikal Bridges,BRK,82.0,82.0,34.8,14.9,0.560,0.457,0.245,2.5,12.0,7.1,16.3,1.4,0.9,10.3,24.3,2.1,2.1,4.2,0.070,0.7,-1.0,-0.4,1.2
4,Paolo Banchero,ORL,80.0,80.0,35.0,17.3,0.546,0.249,0.397,3.4,20.0,11.6,25.2,1.3,1.6,13.0,29.7,1.3,4.0,5.3,0.090,1.3,0.0,1.3,2.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567,Malcolm Cazalon,DET,1.0,0.0,3.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,-0.012,-6.0,-3.2,-9.1,0.0
568,Jalen Crutcher,NOP,1.0,0.0,3.0,-12.6,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.5,0.0,0.0,0.0,-0.334,-18.5,-7.8,-26.2,0.0
569,Dmytro Skapintsev,NYK,2.0,0.0,1.0,-19.3,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.6,0.0,0.0,0.0,-0.483,-16.0,-9.8,-25.9,0.0
570,Justin Jackson,MIN,2.0,0.0,0.5,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.031,-6.3,-1.2,-7.5,0.0
571,Javonte Smart,PHI,1.0,0.0,1.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.005,-6.2,-2.1,-8.3,0.0

                      Player     FGA    FG%    3P%    FT%   eFG%     PTS
0                Luka Dončić  1652.0  0.487  0.382  0.786  0.573  2370.0
1    Shai Gilgeous-Alexander  1487.0  0.535  0.353  0.874  0.567  2254.0
2      Giannis Antetokounmpo  1369.0  0.611  0.274  0.657  0.624  2222.0
3              Jalen Brunson  1648.0  0.479  0.401  0.847  0.543  2212.0
4               Nikola Jokić  1411.0  0.583  0.359  0.817  0.612  2085.0
..                       ...     ...    ...    ...    ...    ...     ...
730              Danny Green     2.0  0.000  0.000    NaN  0.000     0.0
731           Ron Harper Jr.     0.0    NaN    NaN    NaN    NaN     0.0
732           Justin Jackson     0.0    NaN    NaN    NaN    NaN     0.0
733        Dmytro Skapintsev     1.0  0.000    NaN    NaN  0.000     0.0
734            Javonte Smart     0.0    NaN    NaN    NaN    NaN     0.0

[572 rows x 7 columns]

In [167]:
pd.set_option('display.max_columns', None)
a = pd.merge(player_stats_, player_stats_2, how='outer')
b = pd.merge(a, mvp_stats_, how='outer')
c = pd.merge(b, team_stats_, how='outer')
c

,Player,Team,G,GS,MP,PER,TS%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,FGA,FG%,3P%,FT%,eFG%,PTS,Share,W/L%,Seed
0,DeMar DeRozan,CHI,79.0,79.0,37.8,19.7,0.584,0.166,0.452,1.6,11.3,6.4,21.8,1.5,1.5,7.7,25.8,7.0,2.2,9.2,0.147,2.1,-0.3,1.8,2.8,1355.0,0.480,0.333,0.853,0.507,1897.0,0.000,0.476,9.0
1,Coby White,CHI,79.0,78.0,36.5,14.5,0.570,0.460,0.215,1.7,12.4,6.9,20.8,0.9,0.6,11.1,22.7,3.1,1.6,4.7,0.078,0.7,-1.3,-0.7,0.9,1209.0,0.447,0.376,0.838,0.534,1509.0,0.000,0.476,9.0
2,Nikola Vučević,CHI,76.0,74.0,34.3,17.7,0.540,0.258,0.107,8.8,25.8,17.1,15.2,1.0,2.4,8.6,23.3,2.7,2.8,5.4,0.100,0.8,-0.7,0.1,1.4,1211.0,0.484,0.294,0.822,0.522,1370.0,0.000,0.476,9.0
3,Ayo Dosunmu,CHI,76.0,37.0,29.1,13.4,0.604,0.410,0.146,2.7,8.3,5.5,15.6,1.5,1.7,11.9,17.2,2.6,1.5,4.1,0.089,-0.6,-0.2,-0.8,0.7,719.0,0.501,0.403,0.810,0.583,924.0,0.000,0.476,9.0
4,Alex Caruso,CHI,71.0,57.0,28.7,14.5,0.613,0.616,0.177,3.3,11.8,7.5,16.4,2.9,3.5,14.9,14.7,2.3,2.6,4.9,0.115,0.2,2.3,2.5,2.3,541.0,0.468,0.408,0.760,0.593,715.0,0.000,0.476,9.0
5,Andre Drummond,CHI,79.0,10.0,17.1,23.0,0.576,0.006,0.454,21.5,37.4,29.3,4.1,2.7,3.6,12.3,21.3,2.3,2.6,4.9,0.175,0.8,-0.7,0.1,0.7,480.0,0.556,0.000,0.592,0.556,663.0,0.000,0.476,9.0
6,Patrick Williams,CHI,43.0,30.0,27.3,11.0,0.553,0.412,0.184,4.3,11.7,7.9,7.7,1.7,2.9,12.8,16.6,0.1,1.0,1.2,0.048,-2.1,-0.1,-2.3,-0.1,359.0,0.443,0.399,0.788,0.525,429.0,0.000,0.476,9.0
7,Torrey Craig,CHI,53.0,14.0,19.8,10.8,0.568,0.610,0.143,7.2,16.1,11.6,7.3,1.4,2.1,10.7,12.5,1.0,0.9,1.9,0.087,-1.8,-0.2,-2.0,0.0,251.0,0.430,0.392,0.750,0.550,303.0,0.000,0.476,9.0
8,Jevon Carter,CHI,72.0,0.0,13.9,8.5,0.485,0.641,0.019,1.2,5.6,3.3,12.9,1.8,1.6,8.9,17.7,-0.5,0.7,0.2,0.009,-3.3,-0.7,-4.0,-0.5,365.0,0.378,0.329,0.571,0.484,357.0,0.000,0.476,9.0
9,Zach LaVine,CHI,25.0,23.0,34.9,15.1,0.578,0.449,0.274,1.0,15.8,8.3,16.8,1.2,0.9,11.0,23.8,0.8,0.6,1.5,0.080,0.8,-0.7,0.1,0.5,376.0,0.452,0.349,0.854,0.531,487.0,0.000,0.476,9.0
10,Dalen Terry,CHI,59.0,2.0,11.5,10.2,0.512,0.471,0.274,4.7,14.1,9.3,15.6,2.0,2.7,15.4,13.4,0.1,0.7,0.8,0.060,-3.4,1.1,-2.3,0.0,157.0,0.439,0.230,0.581,0.494,180.0,0.000,0.476,9.0
11,Julian Phillips,CHI,40.0,0.0,8.1,7.0,0.521,0.494,0.247,4.1,8.5,6.2,5.3,1.1,2.2,10.5,13.0,0.0,0.2,0.2,0.031,-4.7,-0.6,-5.3,-0.3,77.0,0.416,0.316,0.684,0.494,89.0,0.000,0.476,9.0
12,Onuralp Bitim,CHI,23.0,1.0,11.7,5.0,0.464,0.524,0.060,2.5,11.1,6.7,6.5,0.6,0.8,10.4,15.8,-0.3,0.1,-0.1,-0.027,-5.4,-2.0,-7.4,-0.4,84.0,0.381,0.273,0.800,0.452,80.0,0.000,0.476,9.0
13,Javonte Green,CHI,9.0,5.0,25.6,20.2,0.681,0.360,0.173,9.5,23.3,16.3,3.3,2.2,3.6,8.0,16.7,0.5,0.3,0.9,0.180,1.9,0.1,2.0,0.2,75.0,0.600,0.370,0.769,0.667,110.0,0.000,0.476,9.0
14,Terry Taylor,CHI,31.0,0.0,6.1,10.1,0.558,0.231,0.128,9.9,12.1,11.0,7.0,1.3,1.1,14.5,11.3,0.1,0.1,0.3,0.070,-3.1,-0.1,-3.2,0.0,39.0,0.513,0.222,0.800,0.538,46.0,0.000,0.476,9.0
15,Adama Sanogo,CHI,9.0,0.0,7.3,21.9,0.558,0.000,0.444,31.6,29.4,30.5,0.0,0.8,0.0,13.4,24.8,0.1,0.1,0.2,0.133,-0.4,-6.3,-6.7,-0.1,27.0,0.519,0.000,0.667,0.519,36.0,0.000,0.476,9.0
16,Henri Drell,CHI,4.0,0.0,7.5,10.7,0.506,0.600,0.200,3.7,11.4,7.5,18.3,3.3,3.4,15.5,18.8,0.0,0.0,0.0,0.047,-5.1,0.2,-4.9,0.0,10.0,0.400,0.333,0.500,0.500,11.0,0.000,0.476,9.0
17,Andrew Funk,CHI,5.0,0.0,2.6,-5.0,0.000,0.750,0.000,0.0,0.0,0.0,0.0,3.8,7.9,0.0,13.5,-0.1,0.0,-0.1,-0.252,-12.4,-2.0,-14.4,0.0,4.0,0.000,0.000,0.000,0.000,0.0,0.000,0.476,9.0
18,Domantas Sabonis,SAC,82.0,82.0,35.7,23.2,0.637,0.081,0.389,11.0,32.3,21.4,33.9,1.2,1.5,17.9,22.2,8.6,4.0,12.6,0.206,4.0,2.4,6.5,6.2,1068.0,0.594,0.379,0.704,0.609,1593.0,0.003,0.561,9.0
19,De'Aaron Fox,SAC,74.0,74.0,35.9,20.1,0.567,0.374,0.273,2.8,11.8,7.2,25.2,2.7,1.1,10.1,31.0,3.3,3.2,6.5,0.117,2.6,0.1,2.7,3.2,1549.0,0.465,0.369,0.738,0.534,1966.0,0.000,0.561,9.0
20,Keegan Murray,SAC,77.0,77.0,33.6,13.3,0.569,0.524,0.127,4.5,13.9,9.1,6.9,1.5,2.1,5.9,18.1,2.6,2.6,5.2,0.096,-0.4,-0.5,-0.9,0.8,975.0,0.454,0.358,0.831,0.548,1172.0,0.000,0.561,9.0
21,Harrison Barnes,SAC,82.0,82.0,29.0,11.9,0.611,0.526,0.268,3.1,8.8,5.9,5.6,1.1,0.5,6.6,15.7,3.1,1.5,4.7,0.094,-0.6,-1.2,-1.8,0.1,732.0,0.474,0.387,0.801,0.576,1000.0,0.000,0.561,9.0
22,Malik Monk,SAC,72.0,0.0,26.0,16.0,0.564,0.474,0.230,1.6,11.3,6.3,28.9,1.2,1.9,13.2,25.9,1.9,1.6,3.5,0.090,1.5,-1.0,0.6,1.2,893.0,0.443,0.350,0.829,0.526,1110.0,0.000,0.561,9.0
23,Kevin Huerter,SAC,64.0,59.0,24.4,12.4,0.564,0.609,0.084,2.7,13.6,8.0,14.4,1.4,1.3,8.4,17.3,1.5,1.4,2.9,0.089,-0.5,-0.4,-0.8,0.5,560.0,0.443,0.361,0.766,0.553,655.0,0.000,0.561,9.0
24,Trey Lyles,SAC,58.0,0.0,20.0,11.9,0.596,0.682,0.218,5.8,19.4,12.4,8.1,0.7,1.5,9.7,14.4,1.3,1.0,2.4,0.098,-0.4,-0.7,-1.1,0.3,321.0,0.445,0.384,0.700,0.576,419.0,0.000,0.561,9.0
25,Davion Mitchell,SAC,72.0,4.0,15.3,9.3,0.555,0.489,0.130,1.9,7.9,4.8,16.0,0.7,0.2,11.2,14.9,0.8,0.6,1.3,0.059,-2.4,-1.0,-3.4,-0.4,323.0,0.452,0.361,0.714,0.540,379.0,0.000,0.561,9.0
26,Keon Ellis,SAC,57.0,21.0,17.2,12.0,0.627,0.724,0.151,3.6,10.8,7.1,11.1,2.5,2.7,13.0,12.4,1.1,1.2,2.3,0.114,-0.9,2.1,1.2,0.8,232.0,0.461,0.417,0.743,0.612,310.0,0.000,0.561,9.0
27,Chris Duarte,SAC,59.0,11.0,12.2,8.4,0.512,0.605,0.157,4.0,12.7,8.3,7.8,1.9,1.0,10.4,14.9,0.0,0.7,0.7,0.047,-3.5,0.1,-3.4,-0.2,210.0,0.381,0.346,0.788,0.486,230.0,0.000,0.561,9.0
28,Sasha Vezenkov,SAC,42.0,0.0,12.2,13.3,0.569,0.628,0.079,6.4,14.8,10.5,5.1,1.9,1.3,5.7,17.5,0.5,0.5,1.0,0.098,-0.2,-0.7,-0.9,0.1,191.0,0.440,0.375,0.800,0.558,225.0,0.000,0.561,9.0
29,Alex Len,SAC,48.0,0.0,9.2,14.7,0.625,0.037,0.420,11.3,21.2,16.1,14.4,1.2,6.8,22.0,11.8,0.6,0.7,1.3,0.138,-2.7,2.9,0.2,0.2,81.0,0.617,0.000,0.588,0.617,120.0,0.000,0.561,9.0
30,JaVale McGee,SAC,46.0,0.0,7.4,19.0,0.609,0.053,0.341,13.6,28.4,20.8,7.6,2.0,5.4,18.3,23.4,0.1,0.6,0.7,0.101,-1.9,0.6,-1.3,0.1,132.0,0.598,0.143,0.578,0.602,185.0,0.000,0.561,9.0
31,Kessler Edwards,SAC,54.0,0.0,5.1,10.3,0.541,0.634,0.110,3.6,13.7,8.5,7.1,1.8,1.3,4.4,14.0,0.2,0.3,0.5,0.083,-1.6,0.1,-1.5,0.0,82.0,0.415,0.385,0.556,0.537,93.0,0.000,0.561,9.0
32,Colby Jones,SAC,30.0,0.0,6.4,8.9,0.422,0.310,0.155,9.7,13.7,11.7,13.9,1.8,2.4,11.6,19.1,-0.2,0.2,0.0,0.007,-5.4,0.4,-5.0,-0.1,71.0,0.394,0.091,0.545,0.408,64.0,0.000,0.561,9.0
33,Juan Toscano-Anderson,SAC,11.0,0.0,4.8,2.5,0.292,0.333,0.000,8.3,21.6,14.8,9.0,0.9,1.7,14.3,11.3,-0.1,0.1,0.0,-0.024,-8.7,-0.6,-9.4,-0.1,12.0,0.250,0.250,0.000,0.292,7.0,0.000,0.561,9.0
34,Jalen Slawson,SAC,12.0,0.0,3.1,6.6,0.667,0.333,0.000,3.0,18.6,10.6,6.9,1.3,2.5,25.0,9.2,0.0,0.0,0.0,0.058,-7.5,1.1,-6.4,0.0,6.0,0.667,0.000,0.000,0.667,8.0,0.000,0.561,9.0
35,Mason Jones,SAC,5.0,0.0,5.6,5.8,0.394,0.875,0.250,3.9,16.4,10.0,21.7,1.7,0.0,18.4,16.6,0.0,0.0,0.0,-0.018,-5.4,0.0,-5.5,0.0,8.0,0.250,0.286,0.500,0.375,7.0,0.000,0.561,9.0
36,Jordan Ford,SAC,6.0,0.0,3.7,16.8,0.761,0.429,0.286,0.0,10.4,5.1,12.8,0.0,0.0,11.3,17.3,0.1,0.0,0.1,0.157,3.3,-1.1,2.2,0.0,7.0,0.571,0.667,1.000,0.714,12.0,0.000,0.561,9.0
37,Filip Petrušev,SAC,3.0,0.0,3.3,5.1,0.521,0.000,1.000,0.0,11.2,5.5,0.0,0.0,0.0,0.0,12.3,0.0,0.0,0.0,0.029,-4.7,-3.3,-8.0,0.0,2.0,0.500,0.000,0.500,0.500,3.0,0.000,0.561,9.0
38,Mikal Bridges,BRK,82.0,82.0,34.8,14.9,0.560,0.457,0.245,2.5,12.0,7.1,16.3,1.4,0.9,10.3,24.3,2.1,2.1,4.2,0.070,0.7,-1.0,-0.4,1.2,1294.0,0.436,0.372,0.814,0.521,1606.0,0.000,0.390,11.0
39,Dennis Schröder,BRK,80.0,58.0,31.1,13.3,0.550,0.397,0.230,1.7,9.2,5.3,28.0,1.2,0.6,13.0,20.3,2.3,1.0,3.3,0.063,-0.5,-1.3,-1.8,0.1,927.0,0.435,0.375,0.836,0.509,1122.0,0.000,0.390,11.0
40,Nic Claxton,BRK,71.0,71.0,29.8,18.7,0.629,0.009,0.337,9.7,27.3,18.2,10.4,1.1,6.2,12.2,15.6,3.5,3.2,6.7,0.152,-0.3,1.5,1.2,1.7,582.0,0.629,0.200,0.551,0.630,841.0,0.000,0.390,11.0
41,Cam Thomas,BRK,66.0,51.0,31.4,16.1,0.554,0.333,0.281,1.4,10.1,5.6,15.7,1.1,0.7,8.5,30.5,1.3,1.2,2.5,0.058,0.7,-1.9,-1.2,0.4,1190.0,0.442,0.364,0.856,0.503,1482.0,0.000,0.390,11.0
42,Dorian Finney-Smith,BRK,68.0,56.0,28.4,10.1,0.546,0.658,0.090,6.0,12.1,9.0,7.6,1.4,1.8,10.0,13.2,1.0,1.6,2.6,0.065,-2.0,-0.1,-2.0,0.0,511.0,0.421,0.348,0.717,0.535,580.0,0.000,0.390,11.0
43,Cameron Johnson,BRK,58.0,47.0,27.6,14.5,0.582,0.570,0.176,3.7,13.8,8.6,12.9,1.5,0.8,7.9,19.6,2.0,1.3,3.3,0.100,0.9,-0.5,0.4,1.0,619.0,0.446,0.391,0.789,0.557,776.0,0.000,0.390,11.0
44,Dennis Smith Jr.,BRK,56.0,2.0,18.9,13.4,0.508,0.322,0.172,5.0,12.1,8.5,27.3,3.2,1.0,15.8,17.7,0.5,1.3,1.8,0.080,-2.6,1.8,-0.8,0.3,338.0,0.435,0.294,0.741,0.482,369.0,0.000,0.390,11.0
45,Lonnie Walker IV,BRK,58.0,0.0,17.4,13.1,0.545,0.551,0.120,1.4,12.7,6.9,11.5,1.6,1.8,9.0,24.4,-0.1,0.9,0.8,0.038,-0.4,-1.0,-1.4,0.2,492.0,0.423,0.384,0.763,0.528,565.0,0.000,0.390,11.0
46,Day'Ron Sharpe,BRK,61.0,1.0,15.1,20.0,0.596,0.051,0.418,18.6,27.9,23.1,14.0,1.3,4.3,16.7,19.7,1.6,1.3,2.9,0.152,-0.4,0.4,0.0,0.5,294.0,0.571,0.267,0.610,0.578,415.0,0.000,0.390,11.0
47,Trendon Watford,BRK,63.0,2.0,13.6,15.7,0.611,0.219,0.312,6.5,18.7,12.4,14.6,1.3,2.0,15.1,21.1,0.9,0.9,1.8,0.100,-0.9,0.4,-0.5,0.3,311.0,0.527,0.397,0.794,0.571,432.0,0.000,0.390,11.0
48,Jacob Gilyard,BRK,41.0,14.0,17.0,11.1,0.573,0.840,0.013,1.4,6.0,3.6,27.7,2.3,0.7,16.6,11.1,0.8,0.6,1.4,0.095,-2.0,0.6,-1.4,0.1,150.0,0.400,0.405,1.000,0.570,173.0,0.000,0.390,11.0
49,Keita Bates-Diop,BRK,53.0,8.0,12.5,11.5,0.534,0.416,0.253,5.5,12.8,9.3,7.4,1.8,2.9,7.5,13.0,0.5,0.8,1.3,0.091,-1.5,0.4,-1.0,0.2,166.0,0.434,0.304,0.762,0.497,197.0,0.000,0.390,11.0